version: '3.4'
services:
  postgres:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: dev
    image: blog_django
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    command: python src/manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/static
      - media:/media
  memcached:
    image: memcached
    ports:
      - '11211:11211'
    entrypoint:
      - memcached
      - -m 92
  bootstrap:
    image: blog_django
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 20s
    depends_on:
      - postgres
      - django
    command: python src/manage.py bootstrap
    volumes:
      - .:/code
      - static:/static
      - media:/media
volumes:
  pg-data:
    driver: local
  static:
    driver: local
  media:
    driver: local
