# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='views count'),
        ),
    ]
