# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180423_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='similar',
            field=models.ManyToManyField(blank=True, related_name='_article_similar_+', to='articles.Article'),
        ),
    ]
